# Generated by Django 3.0.5 on 2022-10-15 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=100)),
                ('friends', models.ManyToManyField(blank=True, related_name='_user_friends_+', to='api.User')),
            ],
        ),
    ]
