# Generated by Django 3.0.5 on 2022-10-15 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20221015_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='friends',
        ),
        migrations.DeleteModel(
            name='UserFriends',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
