# Generated by Django 3.0.5 on 2022-10-15 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20221015_2215'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friendship',
            unique_together={('user_one', 'user_two')},
        ),
    ]
